server:
  port: 8080
spring:
  application:
    name: hm-gateway
  cloud:
    nacos:
      server-addr: 192.168.12.6:8848
    gateway:
      routes:
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
            - Method=GET,POST
        - id: item
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
          filters:
            - AddRequestHeader=testStr,hello itheima


#          predicates:
#            - Path=/api/items/**,/search/**
#          filters:
#            -StripePrefix=1    #路由到后端微服务的时候要移除前缀 ：1 表示移除1哥：2表示移除2；个





        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay/**